# Make 'generators' a package
# Import functions to make them easily accessible from PuzzleGenerator
from puzzle.generators.symbol_cipher_gen import generate_symbol_puzzle_internal
from puzzle.generators.logic_grid_gen import generate_logic_grid_puzzle_internal
from puzzle.generators.social_deduction_gen import generate_social_deduction_puzzle_internal
from puzzle.generators.common_sense_gen import generate_common_sense_gap_puzzle_internal
from puzzle.generators.relationship_map_gen import generate_relationship_map_puzzle_internal
from puzzle.generators.ordering_gen import generate_ordering_puzzle_internal
from puzzle.generators.scheduling_gen import generate_scheduling_puzzle_internal
from puzzle.generators.dilemma_gen import generate_dilemma_puzzle_internal
from puzzle.generators.agent_simulation_gen import generate_agent_simulation_puzzle_internal